### ISSUE TITLE
detail the parameters of the HuaweiSolar.env file

### ISSUE THREAD

**Issue by kurb77** [GoumJer/Huawei_Sun2000#1]
Hello,
can you detail the parameters of the HuaweiSolar.env file.
- where i need to put my API acces, ?
- what is myDomoticzHuaweiTokenTimeStampID ?
- what is myInfluxXXX ?

thank you

**Comment by GoumJer** [comment]
Hi,

thanks for your comment, Made me realize I had to document more/better. Added extra info in the .env file and also extended the readme.

As per your questions:

- where i need to put my API acces, ?
Your username and systemcode go into the .env file. You should receive these from Huawei. Third you need is the station ID. I included a reference to the Huawei documentation on how to retreive this. Might be that I will implement this in the script with special parameter. Should not be that difficult.

- what is myDomoticzHuaweiTokenTimeStampID ?
This user variable holds the timestamp of the last retreived token. A token is only valid for 30 minutes. Script checks the age of the token. If it is > 25 minutes it will retreive a fresh one and update this variable.

- what is myInfluxXXX ?
-The myInfluxxxx variables are used to connect to your Influx database (if it is used) If you don't use influx, just leave them there. These are only used for the daily/monthly/yearly data collection. 

Kind regards,
Jeroen

**Comment by kurb77** [comment]
can you confirm that, 
huwawei sent me a System name, a User name, and Password, so

```
userName=User name
systemCode=System name
stationCode=Password
```
thank you
jerome

**Comment by GoumJer** [comment]
Hi Jerome,

Huawei will sent you a username and systemcode. With these you can retreive the stationcode via Postman. Please see the link to Huawei documentation in the readme.

I'm already working on implementing this in my script. Expect that to be ready and available this week

Kind regards,
Jeroen

**Comment by kurb77** [comment]
yes, i readed your explain, i will try to retreive the stationcode via Postman

thank you
jeromle

**Comment by kurb77** [comment]
your script need jg, this not write on the doc.
and there are a mistake when you run the first time
`
./HuaweiSolar_API.sh: ligne 52: ./get_token.sh: Aucun fichier ou dossier de ce type
cat: ./last.token: Aucun fichier ou dossier de ce type

thank you
jerome

**Comment by GoumJer** [comment]
Hi Jerome, I added the option to retreive the stationCode frm huawei to the script. Also added the script which is required to retreive a fresh token (was somehow not included).

Feel free to to test.

Kind regards,
Jeroen

**Comment by kurb77** [comment]
Hello,
i tried, but a had a error

jq: error (at <stdin>:4): Cannot iterate over null (null)
